<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>iBMSC.My.MyApplication</StartupObject>
    <AssemblyName>μBMSC</AssemblyName>
    <MyType>WindowsForms</MyType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>μBMSC.xml</DocumentationFile>
    <Optimize>True</Optimize>
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
    <DocumentationFile>μBMSC.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <AssemblyTitle>μBMSC Editor</AssemblyTitle>
    <Description>iBMS by Doaz Patched by zardoru</Description>
    <Company>iBMS</Company>
    <Product>μBMSC</Product>
    <Copyright>Copyright %28C%29 [4th Age]</Copyright>
    <AssemblyVersion>3.5.0.0</AssemblyVersion>
    <FileVersion>3.5.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <ImportedNamespaces>System.Drawing=False,System.Drawing.Imaging=False,System.IO=False,System.Runtime.InteropServices=False,System.Windows.Forms=False,System.Windows.Forms.Automation=False,System.Windows.Forms.ComponentModel.Com2Interop=False,System.Windows.Forms.Design=False,System.Windows.Forms.Design.Behavior=False,System.Windows.Forms.Layout=False,System.Windows.Forms.PropertyGridInternal=False,System.Windows.Forms.VisualStyles=False,System.Xml=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,iBMSC=True</ImportedNamespaces>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <Import Include="System.Drawing" />
    <Import Include="System.Drawing.Imaging" />
    <Import Include="System.IO" />
    <Import Include="System.Runtime.InteropServices" />
    <Import Include="System.Windows.Forms" />
    <Import Include="System.Windows.Forms.Automation" />
    <Import Include="System.Windows.Forms.ComponentModel.Com2Interop" />
    <Import Include="System.Windows.Forms.Design" />
    <Import Include="System.Windows.Forms.Design.Behavior" />
    <Import Include="System.Windows.Forms.Layout" />
    <Import Include="System.Windows.Forms.PropertyGridInternal" />
    <Import Include="System.Windows.Forms.VisualStyles" />
    <Import Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Dialogs\AboutBox1.designer.vb">
      <DependentUpon>AboutBox1.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\ColorPicker.designer.vb">
      <DependentUpon>ColorPicker.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\dgImportSM.designer.vb">
      <DependentUpon>dgImportSM.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\dgMyO2.designer.vb">
      <DependentUpon>dgMyO2.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\dgStatistics.designer.vb">
      <DependentUpon>dgStatistics.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\diagFind.designer.vb">
      <DependentUpon>diagFind.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\fLoadFileProgress.designer.vb">
      <DependentUpon>fLoadFileProgress.vb</DependentUpon>
    </Compile>
    <Compile Update="Dialogs\SplashScreen1.Designer.vb">
      <DependentUpon>SplashScreen1.vb</DependentUpon>
    </Compile>
    <Compile Update="MainWindow.designer.vb">
      <DependentUpon>MainWindow.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
    <Compile Update="Option Windows\OpGeneral.designer.vb">
      <DependentUpon>OpGeneral.vb</DependentUpon>
    </Compile>
    <Compile Update="Option Windows\OpPlayer.designer.vb">
      <DependentUpon>OpPlayer.vb</DependentUpon>
    </Compile>
    <Compile Update="Option Windows\OpVisual.designer.vb">
      <DependentUpon>OpVisual.vb</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CSCore" Version="1.2.1.2" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="SCompareMethod.Designer.vb" />
    <Compile Remove="SCompareMethod.vb" />
    <EmbeddedResource Remove="SCompareMethod.resx" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Windows\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
</Project>